version: "3.9"
services:
  wiremock:
    container_name: wiremock
    image: wiremock/wiremock:latest
    ports:
      - 7500:8080
    volumes:
      - ./wiremock/__files/:/home/wiremock/__files/
      - ./wiremock/mappings/:/home/wiremock/mappings/

  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017



